name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      run: yarn install

    - name: Yarn build
      run: yarn docs:build
    
