name: Build and deploy archdocstheme to Azure Storage

# set up branch to CI
on:
  push:
    branches:
      - master

# set up env
env:
  OUTPUT_PATH: ${{ github.workspace }}/public
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=reviewarchdocsdesign;AccountKey=mqxSOyMYHt+UUparsoMqfQn+jyLcf2C0/bJNFvZ3U/gj4czZjmURvh6+Bp71BayXXBoseyD8UzTUEQhltla0AQ==;EndpointSuffix=core.windows.net"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    # install package

    - name: Install Dependencies
      run: yarn install

    # build docs

    - name: Yarn build
      run: yarn docs:build --dest ${{ env.OUTPUT_PATH }}

    # Publish

    - name: Publish website output
      uses: actions/upload-artifact@v1.0.0
      with:
        name: website
        path: ${{ env.OUTPUT_PATH }}
    
    - name: Check artifact
      run: |
        ls -la
        ls -la public
        ls -la ${{ env.OUTPUT_PATH }}
        
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
          name: website
          path: ${{ env.OUTPUT_PATH }}

    # deploy
      
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob delete-batch -s \$web --connection-string ${{ env.AZURE_STORAGE_CONNECTION_STRING }}
          az storage blob upload-batch -d \$web -s ${{ env.OUTPUT_PATH }} --connection-string ${{ env.AZURE_STORAGE_CONNECTION_STRING }}
